version: "3.8"

services:
  php-apache:
    container_name: php-apache
    build:
      context: ./php
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
  # This is the database information to build a mysql database container
  db:
    container_name: database
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'secret'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3399:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - "./surgery-db1:/var/lib/mysql"
